version: '3.9'

services:
  app:
    build: ./server/app

    ports:
      - "8080:8080"
  proxy:
    build: ./server/proxy
    environment:
      - ProxyOutAddress=app
    links:
      - app
    ports:
      - "8081:8081"
  client:
    build: ./client
    environment:
      - NetAddress=proxy
    links:
      - proxy
    depends_on:
      - proxy
      - app
